// 「PC・IT入門」タブの内容。初心者向けに、たとえ話を使って説明する。
// 数字は「目安」で、用途や時期によって変わる。買う前には最新の情報で確認する。
// 増やすときは、FIELDS の lessons、GLOSSARY、TIPS に項目を足すだけでOK。

export const FIELDS = [
  {
    id: 'hardware',
    no: 1,
    name: 'パソコンの中身',
    icon: '🔧',
    intro: 'パソコンは部品の組み合わせ。役割を知ると、スペック表が読めるようになる。',
    lessons: [
      {
        title: 'CPU・メモリ・ストレージの違い',
        body: 'この3つは、よく「机と本棚と人」にたとえられる。',
        points: [
          'CPU(Central Processing Unit = 中央処理装置)= 頭脳。計算や処理をする「作業する人」。速いほど、いろいろな処理がサクサク進む。',
          'メモリ(RAM = Random Access Memory)= 作業机の広さ。広いほど、アプリやタブを同時にたくさん開いても重くならない。電源を切ると、中身は消える。',
          'ストレージ = 本棚・倉庫。写真や文書、アプリを保存しておく場所。電源を切っても残る。',
          '「動作が重い」ときは、机(メモリ)が足りないことが多い。「保存できない」ときは、本棚(ストレージ)がいっぱい。',
          '目安: 普通の事務作業ならメモリ8〜16GB。動画編集やAI利用では、32GB以上あると余裕が出る。',
        ],
      },
      {
        title: 'SSDとHDD',
        body: 'どちらもストレージ(保存場所)の種類。',
        points: [
          'SSD(Solid State Drive = 固体ドライブ)= 半導体に保存する。動く部品がないので Solid State。速く、静かで、衝撃にも強い。今のPCはSSDが主流。',
          'HDD(Hard Disk Drive)= 硬い円盤(ディスク)を回して保存する。安くて大容量だが、遅く、動作音がある。',
          'パソコンの起動やアプリの立ち上がりの速さは、SSDかどうかで大きく変わる。',
          'HDDは、写真や動画をたくさん保管する「倉庫」として今も使われる。',
        ],
      },
      {
        title: 'GPUとVRAM',
        body: 'GPU(Graphics Processing Unit = 画像処理装置)は、画像や映像を計算するための専用部品。',
        points: [
          'もともとはゲームや映像のために作られたが、AIの計算にも向いていて、今は重要な部品になっている。',
          'VRAM(Video RAM)= GPU専用のメモリ。AIモデルを動かすときに、このサイズが大事になる(第11分野で詳しく説明)。',
          '内蔵GPU = CPUに入っている。普通の事務作業なら十分。専用GPU = 別の部品として付く。ゲーム・動画・AIに強い。',
        ],
      },
      {
        title: 'スペック表の読み方',
        body: '店のスペック表は、次の順で見ると分かりやすい。',
        points: [
          'CPU: 名前(Intel Core、AMD Ryzen、Apple Mシリーズなど)と、数字。同じシリーズでは、数字が大きいほど上位であることが多い。ただし世代で性能が変わるので、新しいものを選ぶ。',
          'メモリ: 何GBか。増設できるかも確認する(ノートPCは後から増やせないことが多い)。',
          'ストレージ: SSDか、何GB/TBか。256GBだと、すぐいっぱいになりやすい。',
          '画面・重さ・バッテリー: ノートPCでは、持ち運びたいなら重さとバッテリーが大事。',
        ],
      },
      {
        title: 'ノートPCとデスクトップPC',
        body: '使う場所と、将来の拡張で選ぶ。',
        points: [
          'ノートPC = 持ち運べる。部品の交換や増設はしにくい。',
          'デスクトップPC = 大きいが、同じ値段なら高性能。部品を交換でき、長く使える。',
          'AIやゲームで高い性能が必要なら、デスクトップが有利。まず今のPCで試して、足りなければ買い替える進め方がおすすめ。',
        ],
      },
      {
        title: 'マザーボード・電源・冷却',
        body: '地味だが、パソコンを支える大事な部品。',
        points: [
          'マザーボード = すべての部品をつなぐ土台。',
          '電源ユニット = 各部品に電気を送る。高性能な部品ほど、大きな電力が必要。',
          '冷却(ファンなど) = 熱を逃がす。熱がこもると、性能が落ちたり、故障の原因になる。',
        ],
      },
    ],
  },
  {
    id: 'os',
    no: 3,
    name: 'OS・ショートカット',
    icon: '🖥️',
    intro: 'OSは、パソコンを動かす土台。操作を覚えると、毎日の作業がぐっと速くなる。',
    lessons: [
      {
        title: 'OSとは何か',
        body: 'OS(Operating System)は、パソコンの基本ソフト。アプリを動かす土台。',
        points: [
          'Windows = 多くの会社・家庭で使われる。ソフトや周辺機器の選択肢が広い。',
          'macOS = Appleの製品用。デザインや動画制作で人気。',
          'Linux = 無料で公開されているOS。サーバー(他のPCにサービスを提供するPC)でよく使われる。',
          'アプリは、OSごとに作られている。Windows用のソフトは、基本的にMacでは動かない。',
        ],
      },
      {
        title: '最初に覚えたいショートカット',
        body: 'ショートカット = キーの組み合わせで、マウスを使わずに操作する方法。',
        points: [
          'Ctrl + C = コピー / Ctrl + V = 貼り付け / Ctrl + X = 切り取り',
          'Ctrl + Z = 元に戻す / Ctrl + Y = やり直す',
          'Ctrl + A = すべて選択 / Ctrl + S = 保存 / Ctrl + F = 検索',
          'Alt + Tab = 開いているアプリを切り替える',
          'Windowsキー + D = デスクトップを表示 / Windowsキー + E = ファイルを開く / Windowsキー + L = 画面をロック',
          'Windowsキー + Shift + S = 画面の一部を撮る(スクリーンショット)',
        ],
      },
      {
        title: 'ファイルとフォルダの整理',
        body: '散らかったデスクトップは、探す時間のムダになる。',
        points: [
          '拡張子 = ファイル名の最後の部分(.docx は Word、.xlsx は Excel、.pdf は PDFなど)。ファイルの種類を表す。',
          'フォルダ分けの基本: 「仕事」「学習」「写真」など、大きな分類から。深くしすぎない。',
          'ファイル名のルール例: 「2026-10-08_会議メモ」のように、日付を頭につけると、並べ替えたとき時系列になる。',
          '消す前に確認する習慣を。ごみ箱を空にすると、基本的には戻せない。',
        ],
      },
      {
        title: '設定で見ておくと良い場所',
        body: 'Windows 11では、「設定」から確認できる。(画面の表記は更新で変わることがある)',
        points: [
          'システム → ストレージ: 何が容量を使っているか見られる。',
          'アプリ → スタートアップ: パソコン起動時に自動で開くアプリ。不要なものを切ると、起動が軽くなることがある。',
          'Windows Update: 更新プログラム。セキュリティのために、こまめに適用する。',
        ],
      },
      {
        title: 'アップデートはなぜ大事?',
        body: '更新には、機能の追加だけでなく、安全のための修正が含まれる。',
        points: [
          'ソフトの弱点(脆弱性)が見つかると、更新で直される。放置すると、そこを悪用されるおそれがある。',
          '大事な作業の前や、作業中は避け、時間のあるときに更新する。',
        ],
      },
    ],
  },
  {
    id: 'security',
    no: 5,
    name: 'セキュリティ',
    icon: '🔒',
    intro: '難しい知識より、習慣が大事。ここだけ守れば、被害の多くは防げる。',
    lessons: [
      {
        title: 'パスワードの基本',
        body: '「長く」「使い回さない」の2つが最重要。',
        points: [
          '長いほど強い。短く複雑な文字より、長い文のほうが破られにくい。',
          '同じパスワードを複数のサービスで使うと、1つ漏れたとき全部が危なくなる。',
          'たくさん覚えられないので、パスワード管理ソフトを使う方法がある(ブラウザ標準の機能でも、基本は役に立つ)。',
          'パスキー = パスワードの代わりに、指紋や顔で本人確認する新しい方式。対応サービスが増えている。',
        ],
      },
      {
        title: '2段階認証(二要素認証)',
        body: 'パスワードに加えて、もう1つ確認する仕組み。',
        points: [
          'パスワードが漏れても、2つめの確認(スマホのコードなど)がないと入れない。',
          '優先して設定したいのは、メール、銀行・決済、SNS、クラウド。特にメールは「他のサービスの鍵」になるので最優先。',
          '認証アプリのほうが、SMSより安全とされる。',
        ],
      },
      {
        title: 'フィッシング詐欺の見分け方',
        body: '本物そっくりのメールやSMSで、パスワードやカード情報を盗む詐欺。',
        points: [
          '「アカウントが停止されます」「今すぐ確認」など、あわてさせる文面に注意。',
          'メールのリンクは押さず、公式アプリやブックマークから開き直す。',
          '送り主のアドレスを、よく見る。似せた偽物が多い。',
          '怪しいと思ったら、入力せず、公式の窓口で確認する。',
        ],
      },
      {
        title: 'ウイルス(マルウェア)対策',
        body: 'マルウェア = 悪意のあるソフトの総称。',
        points: [
          'Windowsには、標準で「Microsoft Defender」というセキュリティ機能が入っている。まずはこれを有効にしておく。',
          '出どころの分からないファイルや、違法な海賊版ソフトは開かない。',
          'OSとソフトを、常に最新にしておく。',
        ],
      },
      {
        title: 'バックアップの考え方',
        body: '「壊れる前提」で、コピーを持つ。',
        points: [
          '3-2-1ルール: データを3つ持ち、2種類の媒体に分け、1つは別の場所に置く。',
          '例: PC本体 + 外付けディスク + クラウド保存。',
          '大事な写真や文書は、まず「クラウドか外付けにも保存」から始める。',
        ],
      },
      {
        title: 'AIに入力してはいけないもの',
        body: 'AIを使うときも、情報の扱いは同じ。',
        points: [
          'パスワード、クレジットカード番号、マイナンバーなどは入力しない。',
          '会社の機密、お客様の個人情報は、会社のルールで許可された範囲だけ。',
          'サービスによって、入力内容の扱い(学習に使われるか)が違う。設定を確認する。',
        ],
      },
    ],
  },
  {
    id: 'dev',
    no: 9,
    name: 'プログラミング・開発',
    icon: '⌨️',
    intro: 'このアプリ作りで、すでに一部を体験している。何をしていたのかを、ここで整理する。',
    lessons: [
      {
        title: 'プログラミングとは',
        body: 'コンピューターへの「命令書」を書くこと。',
        points: [
          'Python = 読みやすく、初心者向け。データ分析やAIでよく使われる。',
          'JavaScript = Webページを動かす言語。このアプリも、JavaScript(とReact)で作られている。',
          'ほかにも言語はたくさんあるが、目的に合わせて選ぶ。最初は1つで十分。',
        ],
      },
      {
        title: 'ターミナルとコマンド',
        body: 'ターミナル = 文字で命令を打ってPCを操作する画面。',
        points: [
          'コマンド = ターミナルに打つ命令。例: cd フォルダ名 (フォルダを移動する)、npm run dev (アプリを起動する)。',
          'マウスでできることを、文字で正確にくり返せる。自動化に向いている。',
          'このアプリ作りで使った PowerShell も、ターミナルの一種。',
        ],
      },
      {
        title: 'Gitと GitHub',
        body: '作ったものの「変更履歴」を残し、共有する仕組み。',
        points: [
          'Git = 変更の履歴を記録するソフト。いつでも前の状態に戻せる。',
          'GitHub = Gitで管理したコードを置く、インターネット上の保管場所。',
          'コミット = 変更を1つの記録として保存すること。push = 手元の記録をGitHubに送ること。',
          '今回のアプリが公開されているのも、GitHub Pages(無料の公開機能)のおかげ。',
        ],
      },
      {
        title: 'Webの仕組み',
        body: 'ブラウザで見ているページは、3つの言語でできている。',
        points: [
          'HTML = ページの骨組み(見出し、段落、リンクなど)。',
          'CSS = 見た目(色、大きさ、配置)。',
          'JavaScript = 動き(ボタンを押したら変わる、など)。',
          'ブラウザがサーバー(情報を持つコンピューター)にお願いして、ページのデータを受け取り、画面に表示する。',
        ],
      },
      {
        title: 'APIとは',
        body: 'API(Application Programming Interface)は、ソフト同士が会話するための「窓口」。Interface = 接点・窓口。',
        points: [
          'たとえば、天気アプリは、気象のAPIにお願いして、天気を受け取っている。',
          'ClaudeやChatGPTも、APIを使うと、自分のアプリに組み込める。',
          'APIキー = その窓口を使うための鍵。他人に知られると悪用されるので、絶対に公開しない。',
        ],
      },
      {
        title: 'AIと一緒に作るコツ',
        body: 'AIにコードを書いてもらう時代でも、仕組みの理解は役に立つ。',
        points: [
          'エラーが出たら、メッセージをそのままAIに貼って「何が原因?」と聞く。',
          '「何をしたいか」を先に伝えると、まとまった作業を任せられる。',
          '作ったものは、必ず動かして確かめる。AIは間違えることがある。',
          '大きな変更の前は、Gitで保存しておく。失敗しても戻せる。',
        ],
      },
    ],
  },
  {
    id: 'ai-pc',
    no: 11,
    name: 'AIとパソコン',
    icon: '🤖',
    intro: '「自室にAIの環境をつくる」ための基礎。買う前に、知っておきたいこと。',
    lessons: [
      {
        title: 'AIはどこで動いている?',
        body: '大きく2通りある。',
        points: [
          'クラウド型(ChatGPT、Claudeなど) = 事業者の巨大なコンピューターで動く。自分のPCは高性能でなくていい。インターネットが必要。',
          'ローカル型(ローカルLLM) = 自分のPCの中で動く。インターネットなしでも動き、入力内容が外に出ない。ただし、PCの性能が必要。',
          'LLM(Large Language Model = 大規模言語モデル)= 文章を理解して作るAIの仕組み。ChatGPTなどの中身。',
        ],
      },
      {
        title: 'ローカルLLMのメリット・デメリット',
        body: '向いているか、考えてみる。',
        points: [
          'メリット: 利用料がかからない(電気代は別)。データが外に出ない。オフラインで使える。',
          'デメリット: 最先端の大きなAIほどの性能は出ない。高性能なPCが必要。設定に手間がかかる。',
          '「機密を扱う」「通信量や利用料を気にせず試したい」場合に向いている。',
        ],
      },
      {
        title: 'GPUとVRAMが大事な理由',
        body: 'AIは、モデルというデータの塊を、GPUのメモリ(VRAM)に載せて動かす。',
        points: [
          'モデルが大きいほど、VRAMがたくさん必要になる。',
          '目安: 小さめのモデルなら、VRAM 8GB前後から動く。大きめのモデルを快適に動かすには、16〜24GB以上が必要になることが多い。(モデルや設定で変わる)',
          'VRAMが足りないと、動かない、または非常に遅くなる。GPUの「速さ」より、まずVRAMの量を見る。',
        ],
      },
      {
        title: 'メモリとストレージも必要',
        body: 'GPU以外にも、条件がある。',
        points: [
          'システムメモリ: 16GB以上、できれば32GB以上あると余裕がある。',
          'ストレージ: モデルのファイルは、1つで数GB〜数十GBになる。複数ためすなら、SSDの空きが数百GB欲しい。',
          'Appleの最近のMacは、CPUとGPUがメモリを共有する設計(ユニファイドメモリ)で、ローカルLLMに向いているといわれる。',
        ],
      },
      {
        title: 'まずは試してみる方法',
        body: '買う前に、今のPCで試すのが鉄則。',
        points: [
          '入門者向けのソフト: LM Studio、Ollama など(ローカルLLMを動かすための無料ソフト)。',
          '小さめのモデルから試し、速さと答えの質を体感する。',
          '「遅い」「物足りない」と感じたところが、買い替えポイントになる。',
          '機器を買う前に、クラウドAIでも十分か、よく考える。',
        ],
      },
      {
        title: '自室サーバーを考えるとき',
        body: '性能以外にも、考えることがある。',
        points: [
          '電気代: 常時動かすと、月に数千円かかることもある。',
          '騒音と熱: ファンの音、部屋の温度。置き場所も重要。',
          'セキュリティ: 外部からつなぐ設定は、慎重に。初心者は、まず家の中だけで使う。',
          '保守の手間: 更新やトラブル対応は、自分で行う。',
        ],
      },
    ],
  },
]

// 用語集。「どの分野で出てくるか」をfieldに入れておく
export const GLOSSARY = [
  { term: 'CPU', field: 'hardware', body: 'パソコンの頭脳。計算や処理を行う部品。' },
  { term: 'メモリ(RAM)', field: 'hardware', body: '作業机のような一時置き場。広いほど同時にたくさんの作業ができる。電源を切ると消える。' },
  { term: 'ストレージ', field: 'hardware', body: 'データを保存しておく場所。SSDやHDDがある。' },
  { term: 'SSD', field: 'hardware', body: '半導体で保存するストレージ。速くて静か。' },
  { term: 'HDD', field: 'hardware', body: '円盤を回して保存するストレージ。安くて大容量だが遅め。' },
  { term: 'GPU', field: 'hardware', body: '画像や映像、AIの計算が得意な専用部品。' },
  { term: 'VRAM', field: 'hardware', body: 'GPU専用のメモリ。AIモデルを動かすときに重要。' },
  { term: 'マザーボード', field: 'hardware', body: 'パソコンの部品をつなぐ土台の基板。' },
  { term: '電源ユニット', field: 'hardware', body: '各部品に電気を送る装置。' },
  { term: 'BTO', field: 'hardware', body: '「受注生産」のこと。部品を選んで注文し、組み立ててもらって買うパソコン。' },
  { term: 'OS', field: 'os', body: 'パソコンやスマホの基本ソフト。Windows、macOS、Linuxなど。' },
  { term: 'ドライバー', field: 'os', body: '周辺機器(プリンターなど)をPCが使えるようにするための小さなソフト。' },
  { term: 'アップデート', field: 'os', body: 'ソフトを新しくすること。機能追加や、安全のための修正を含む。' },
  { term: 'ショートカット', field: 'os', body: 'キーの組み合わせで、マウスを使わず操作する方法。' },
  { term: '拡張子', field: 'os', body: 'ファイル名の最後の部分。ファイルの種類を表す(.docx、.pdfなど)。' },
  { term: 'Linux', field: 'os', body: '無料で公開されているOS。サーバーでよく使われる。' },
  { term: 'クラウド', field: 'os', body: 'インターネット上のサービスにデータやソフトを置いて使うこと。' },
  { term: 'サーバー', field: 'dev', body: '他のコンピューターに、情報やサービスを提供するコンピューター。' },
  { term: 'ブラウザ', field: 'dev', body: 'Webページを見るソフト(Chrome、Edgeなど)。' },
  { term: '2段階認証', field: 'security', body: 'パスワードに加えて、もう1つ確認して本人と確かめる仕組み。' },
  { term: 'パスキー', field: 'security', body: 'パスワードの代わりに、指紋や顔などで本人確認する新しい方式。' },
  { term: 'フィッシング', field: 'security', body: '本物そっくりのメールやサイトで、パスワードなどを盗む詐欺。' },
  { term: 'マルウェア', field: 'security', body: '悪意のあるソフトの総称。ウイルスなど。' },
  { term: 'VPN', field: 'security', body: '通信を暗号化して、安全な通り道を作る仕組み。公共Wi-Fiなどで使われる。' },
  { term: '暗号化', field: 'security', body: 'データを、鍵がないと読めない形に変えること。' },
  { term: 'バックアップ', field: 'security', body: '万一に備えて、データのコピーを別の場所に保存しておくこと。' },
  { term: 'NAS', field: 'security', body: '家庭やオフィスで使う、ネットワーク経由で使えるデータ保管用の機器。' },
  { term: 'ターミナル', field: 'dev', body: '文字で命令を打って、パソコンを操作する画面。' },
  { term: 'コマンド', field: 'dev', body: 'ターミナルに打つ命令。' },
  { term: 'Git', field: 'dev', body: '変更履歴を記録・管理するソフト。' },
  { term: 'GitHub', field: 'dev', body: 'Gitで管理したコードを置く、インターネット上の保管場所。' },
  { term: 'コミット', field: 'dev', body: '変更を、1つの記録として保存すること。' },
  { term: 'API', field: 'dev', body: 'ソフト同士がやりとりするための窓口。' },
  { term: 'APIキー', field: 'dev', body: 'APIを使うための鍵。他人に知られないように管理する。' },
  { term: 'HTML / CSS / JavaScript', field: 'dev', body: 'Webページを作る3つの言語。骨組み・見た目・動きをそれぞれ担当する。' },
  { term: 'Python', field: 'dev', body: '読みやすく、初心者向けのプログラミング言語。データ分析やAIでよく使われる。' },
  { term: 'React', field: 'dev', body: 'Webの画面を作るための、JavaScriptの部品集(ライブラリ)。このアプリでも使っている。' },
  { term: 'Docker', field: 'dev', body: 'アプリを動かす環境を、そのままひとまとめにして持ち運べる仕組み。' },
  { term: 'LLM', field: 'ai-pc', body: '大規模言語モデル。文章を理解して作るAIの仕組み。' },
  { term: 'ローカルLLM', field: 'ai-pc', body: '自分のPCの中で動かすLLM。' },
  { term: 'モデル', field: 'ai-pc', body: 'AIの「頭脳」にあたるデータの塊。ファイルとして配布される。' },
  { term: 'ユニファイドメモリ', field: 'ai-pc', body: 'CPUとGPUがメモリを共有する設計。Appleの最近のMacで採用されている。' },
  { term: 'PC', field: 'hardware', body: 'パソコン。個人が使うコンピューター。', abbr: { full: 'Personal Computer', ja: '個人用コンピューター' } },
  { term: 'IT', field: 'dev', body: '情報技術。コンピューターや通信の技術全般。', abbr: { full: 'Information Technology', ja: '情報技術' } },
  { term: 'AI', field: 'ai-pc', body: '人間のような知的な処理をするコンピューターの技術。', abbr: { full: 'Artificial Intelligence', ja: '人工知能' } },
  { term: 'GB / TB', field: 'hardware', body: 'データの大きさの単位。1TBは約1000GB。', abbr: { full: 'Gigabyte / Terabyte', ja: 'ギガバイト / テラバイト', note: 'byte(バイト)はデータの基本の単位。G=10億、T=1兆の意味。' } },
  { term: 'USB', field: 'hardware', body: '周辺機器をつなぐ、標準的な接続口。', abbr: { full: 'Universal Serial Bus', ja: '汎用の直列(1本ずつ送る)バス', note: 'Universal=万能の、Bus=データの通り道。' } },
  { term: 'HDMI', field: 'hardware', body: '映像と音声を1本のケーブルで送る接続規格。', abbr: { full: 'High-Definition Multimedia Interface', ja: '高精細マルチメディアの接点' } },
  { term: 'LAN', field: 'security', body: '家や会社などの、狭い範囲のネットワーク。', abbr: { full: 'Local Area Network', ja: '限られた範囲のネットワーク' } },
  { term: 'IPアドレス', field: 'security', body: 'ネットワーク上の機器につける、住所のような番号。', abbr: { full: 'Internet Protocol address', ja: 'インターネットの通信規約で使う住所' } },
  { term: 'DNS', field: 'security', body: 'サイトの名前(例: example.com)を、IPアドレスに変換する仕組み。', abbr: { full: 'Domain Name System', ja: 'ドメイン名の仕組み', note: '「インターネットの電話帳」とも例えられる。' } },
  { term: 'URL', field: 'dev', body: 'Webページの住所。https://... で始まる文字。', abbr: { full: 'Uniform Resource Locator', ja: '統一された資源の所在表記' } },
  { term: 'PDF', field: 'os', body: 'どの環境でも、同じ見た目で表示できる文書形式。', abbr: { full: 'Portable Document Format', ja: '持ち運べる文書形式' } },
  { term: 'CSV', field: 'os', body: 'カンマ(,)で区切った、表のデータを保存する形式。Excelで開ける。', abbr: { full: 'Comma-Separated Values', ja: 'カンマで区切られた値' } },
  { term: 'RPA', field: 'dev', body: 'パソコンの定型作業を、ソフトに自動でやらせる仕組み。', abbr: { full: 'Robotic Process Automation', ja: 'ロボットによる業務の自動化' } },
]

// 略語の元の英語。GLOSSARY の term と同じ文字で書くと、用語集に表示される。
// full = 元の英語、ja = 日本語訳、note = 補足
export const ABBR = {
  'CPU': { full: 'Central Processing Unit', ja: '中央処理装置' },
  'メモリ(RAM)': { full: 'Random Access Memory', ja: '随時に読み書きできる記憶装置', note: '「Random Access」は、好きな場所に直接アクセスできるという意味。' },
  'SSD': { full: 'Solid State Drive', ja: '固体(半導体)ドライブ', note: '回転する部品がなく、固体の部品だけでできているので Solid State。' },
  'HDD': { full: 'Hard Disk Drive', ja: 'ハードディスクドライブ' },
  'GPU': { full: 'Graphics Processing Unit', ja: '画像処理装置' },
  'VRAM': { full: 'Video RAM', ja: '映像用のRAM' },
  'BTO': { full: 'Build To Order', ja: '注文に応じて組み立てる' },
  'OS': { full: 'Operating System', ja: '運用・操作するための基本ソフト' },
  'NAS': { full: 'Network Attached Storage', ja: 'ネットワークにつないだ保存装置' },
  'VPN': { full: 'Virtual Private Network', ja: '仮想的な専用ネットワーク' },
  'API': { full: 'Application Programming Interface', ja: 'アプリ同士をつなぐ接点(窓口)', note: 'Interface = 接点・窓口。' },
  'HTML / CSS / JavaScript': { full: 'HyperText Markup Language / Cascading Style Sheets', ja: 'HTML=文書の構造を記す言語 / CSS=見た目を指定する書式', note: 'JavaScriptは略語ではなく、言語の名前。' },
  'LLM': { full: 'Large Language Model', ja: '大規模言語モデル' },
  'ローカルLLM': { full: 'Local Large Language Model', ja: '手元(ローカル)で動かす大規模言語モデル' },
  'Linux': { full: '(略語ではない)', ja: '作者リーナス・トーバルズ(Linus)の名前と、Unixに由来する名前' },
  'Wi-Fi': { full: '(正式な略語ではない)', ja: '無線LANの規格につけられた商標名', note: 'Wireless Fidelityの略と説明されることもあるが、実際には商標名。' },
}

// 略語によく出てくる英単語。意味を知ると、略語を覚えやすい
export const WORDS = [
  { en: 'Central', ja: '中央' },
  { en: 'Processing', ja: '処理' },
  { en: 'Unit', ja: '装置・単位' },
  { en: 'Memory', ja: '記憶' },
  { en: 'Random Access', ja: '好きな場所に直接アクセスできる' },
  { en: 'Graphics', ja: '画像・図形' },
  { en: 'Solid State', ja: '固体(動く部品がない)' },
  { en: 'Drive', ja: '駆動装置(データを出し入れする装置)' },
  { en: 'Operating System', ja: '運用・操作のための基本ソフト' },
  { en: 'Network', ja: '網・つながり' },
  { en: 'Virtual', ja: '仮想の(実体はないが、そう見える)' },
  { en: 'Private', ja: '専用の・非公開の' },
  { en: 'Local', ja: '手元の・その場所の' },
  { en: 'Area', ja: '範囲・地域' },
  { en: 'Interface', ja: '接点・窓口' },
  { en: 'Application', ja: '応用・アプリ(特定の目的のソフト)' },
  { en: 'Programming', ja: 'プログラムを書くこと' },
  { en: 'Language', ja: '言語' },
  { en: 'Model', ja: '模型・型(AIの頭脳にあたるデータ)' },
  { en: 'Large', ja: '大きい' },
]

// 今日の豆知識。毎日2つ、日付で入れ替わる
export const TIPS = [
  { field: 'os', title: '閉じたタブを復活させる', body: 'ブラウザで Ctrl + Shift + T を押すと、間違えて閉じたタブが戻る。' },
  { field: 'os', title: 'アプリの切り替え', body: 'Alt + Tab で、開いているアプリを素早く切り替えられる。' },
  { field: 'os', title: '画面の一部を撮る', body: 'Windowsキー + Shift + S で、画面の好きな範囲を撮れる。' },
  { field: 'os', title: 'コピーの履歴を使う', body: 'Windowsキー + V で、過去にコピーしたものを選んで貼り付けられる(初回は有効にする設定が必要)。' },
  { field: 'os', title: '画面をすぐロック', body: '席を立つとき、Windowsキー + L で画面を守れる。' },
  { field: 'os', title: '全部を一瞬で隠す', body: 'Windowsキー + D で、全部のウィンドウを隠して、デスクトップを見られる。' },
  { field: 'os', title: '元に戻す', body: 'Ctrl + Z は、ほとんどのソフトで使える。間違えても、あわてない。' },
  { field: 'os', title: 'ページ内の文字を探す', body: 'Ctrl + F で、Webページや文書の中から、言葉を探せる。' },
  { field: 'os', title: 'Excelのショートカット', body: 'Ctrl + Shift + L でフィルターのオン・オフ。大量のデータの絞り込みが速くなる。' },
  { field: 'os', title: 'Excelの選択', body: 'Ctrl + Shift + 矢印キー で、データの端まで一気に選べる。' },
  { field: 'os', title: 'ファイルを開く場所', body: 'Windowsキー + E で、エクスプローラー(ファイルを管理する画面)がすぐ開く。' },
  { field: 'hardware', title: 'メモリが足りないサイン', body: 'ブラウザのタブを増やすと急に重くなるなら、メモリ不足の可能性がある。' },
  { field: 'hardware', title: '容量の確認', body: '「設定 → システム → ストレージ」で、何が容量を使っているか見られる。' },
  { field: 'hardware', title: 'スペック表の見方', body: '「SSD」と書いてあるか確認する。HDDのみだと、起動や動作が遅めになる。' },
  { field: 'hardware', title: '熱に注意', body: 'ノートPCを布団の上で使うと、通気口をふさいで熱がこもる。固い机の上がおすすめ。' },
  { field: 'security', title: 'パスワードは使い回さない', body: '1つ漏れたとき、同じパスワードのサービスがすべて危なくなる。' },
  { field: 'security', title: '2段階認証をまず1つ', body: 'まずはメールのアカウントに設定する。他のサービスの鍵になるから。' },
  { field: 'security', title: '怪しいメールの見分け', body: '「今すぐ」「アカウント停止」で急がせる文面は、まず疑う。リンクではなく、公式アプリから確認する。' },
  { field: 'security', title: 'バックアップの習慣', body: '大事な写真や文書は、PCとは別の場所にも保存しておく。' },
  { field: 'security', title: '更新は後回しにしない', body: 'アップデートには、安全のための修正が含まれる。時間のあるときに、こまめに。' },
  { field: 'dev', title: 'エラーはAIに貼る', body: 'エラーメッセージを、そのままAIに貼って「原因は?」と聞くと、解決が早い。' },
  { field: 'dev', title: 'ターミナルの履歴', body: 'ターミナルで上矢印キーを押すと、前に打ったコマンドが出る。' },
  { field: 'dev', title: 'ターミナルで止める', body: '動いているものを止めたいとき、Ctrl + C を押す。' },
  { field: 'dev', title: 'APIキーは公開しない', body: 'GitHubなど、誰でも見られる場所に、APIキーを置かない。' },
  { field: 'dev', title: '試す前に保存', body: '大きな変更の前は、Gitでコミット(保存)しておくと、失敗しても戻せる。' },
  { field: 'ai-pc', title: 'VRAMを見る', body: 'ローカルLLMでは、GPUの速さより、まずVRAMの量を確認する。' },
  { field: 'ai-pc', title: '買う前に試す', body: 'AI用の機材を買う前に、今のPCで小さなモデルを試すと、必要な性能が分かる。' },
  { field: 'ai-pc', title: '電気代も計算', body: '自室サーバーを常時動かすと、電気代がかかる。使う時間と消費電力を確認する。' },
  { field: 'ai-pc', title: 'ローカルとクラウドの使い分け', body: '機密を扱うならローカル、最高性能が必要ならクラウド、という考え方がある。' },
]
